name: DotnetUnitTest

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  DOTNET_VERSION: "8.0.x"

jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Run Unit Test
        run: dotnet test -c Release --no-build --logger "console;verbosity=detailed"
